### ISSUE TITLE
fix: the npm package is empty

### ISSUE THREAD

**Issue by JimmyLv** [SpellcraftAI/nextjs-edge-cors#1]
<img width="590" alt="BibiGPT  ~cAIBibiGPT  – …node_modulesnextjs-edge-corspackage json-WebStorm" src="https://github.com/SpellcraftAI/nextjs-edge-cors/assets/4997466/7a6dba04-6212-47cb-ae5e-173a207b5c01">

**Comment by ctjlewis** [comment]
Sorry about that. Docs are updated, new version's up.

### Demo
https://nextjs-edge-cors.vercel.app/api/cors
See: https://github.com/SpellcraftAI/nextjs-cors-demo

### Example

```ts
// src/middleware.ts

import { CorsMiddleware } from "nextjs-edge-cors";

export const middleware = CorsMiddleware({
  origin: "*"
})

export const config = {
  matcher: ["/api/cors/:path*"]
};
```
